source-file "${HOME}/.tmux-themepack/powerline/block/cyan.tmuxtheme"

set -g renumber-windows on
set -g history-limit 10000

# split panes with | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# switch panes with arrow keys
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# improve new window binding
bind "c" new-window -c "#{pane_current_path}"

# enable mouse mode
set -g mouse on

bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"
