#!/usr/bin/env sh

yabai -m config layout bsp

yabai -m config top_padding 20
yabai -m config bottom_padding 20
yabai -m config left_padding 20
yabai -m config right_padding 20
yabai -m config window_gap 20

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Tweetbot" manage=off
